### PR TITLE
Changes to date parsing in Routes.php

### PR DESCRIPTION
**Pull request by aduitsis**
As discussed over email, here is a small patch to handle extended date strings. Went a little overboard with the DateTime::createFromFormat modifications, hope those changes are acceptable. If not, please reject with a trifle of feedback so that I will know what to adjust.

### CODE REVIEW

**Comment by barryo** [comment]
Hi @aduitsis - I'll have a look at this today / soon. I may edit the regex's a little.

Can you confirm that you submit this under the existing [MIT license](https://github.com/inex/birdseye/blob/master/LICENSE.md)?

**Comment by aduitsis** [comment]
Hello @barryo, yes, same license the original software.

**Comment by aduitsis** [comment]
I suspect you might want to put \s+ instead of literal ' '-space or try to work out a more explicit pattern to get the date. Obviously no problem in any case.

**Comment by barryo** [comment]
Thanks @aduitsis - merged into master.

Let me know if it works for you and I'll stamp it as v1.0.5 and release.

**Comment by aduitsis** [comment]
Date parsing is okay afaict. 

If you are going to make a release, could you please include a tarball like in 1.0.3 so that there won't be a need to issue composer update, etc?

**Comment by barryo** [comment]
Done: https://github.com/inex/birdseye/releases/tag/v1.0.5

**Pull request merged**
